apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: t0c9i009d-python
  janus-idp.io/tekton: t0c9i009d-python
  backstage.io/kubernetes-id: t0c9i009d-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: t0c9i009d-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
