apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: t0c9i009d-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: t0c9i009d-python 
  name: t0c9i009d-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: t0c9i009d-python 
